dist-tags:
  'v12.x': 'v12'
  'v13.x': 'latest'
  'master': 'next'

labels:
  ':package: v12': 'v12.x'
  ':package: v13': 'v13.x'

release-pr-branch-pattern: 'release-bot/next-%s'

prepare-release-command: 'yarn release:prepare'
