
module.exports = {
  'rules': {
    'block-no-empty': true,
    'block-no-single-line': true,
    'color-hex-case': 'lower',
    'color-no-invalid-hex': true,
    'declaration-block-trailing-semicolon': 'always',
    'declaration-colon-space-after': 'always',
    'declaration-colon-space-before': 'never',
    'declaration-no-important': true,
    'font-family-name-quotes': 'always-where-required',
    'function-comma-space-after': 'always',
    'function-url-quotes': 'always',
    'indentation': 2,
    'media-feature-colon-space-after': 'always',
    'media-feature-colon-space-before': 'never',
    'media-feature-name-no-vendor-prefix': true,
    'max-empty-lines': 2,
    'max-nesting-depth': 2,
    'no-eol-whitespace': true,
    'number-leading-zero': 'never',
    'number-max-precision': 2,
    'number-no-trailing-zeros': true,
    'number-zero-length-no-unit': true,
    'property-no-vendor-prefix': true,
    'selector-list-comma-space-before': 'never',
    'selector-list-comma-newline-after': 'always',
    'selector-max-empty-lines': 0,
    'selector-no-id': true,
    'selector-no-qualifying-type': true,
    'selector-no-type': true,
    'selector-no-universal': true,
    'string-quotes': 'single',
    'value-no-vendor-prefix': true
  }
};
